In [1]:
!pip install rdkit

Collecting rdkit
  Downloading rdkit-2026.3.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rdkit) (2.0.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from rdkit) (11.3.0)
Downloading rdkit-2026.3.1-cp312-cp312-manylinux_2_28_x86_64.whl (37.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.0/37.0 MB 47.0 MB/s eta 0:00:00
Installing collected packages: rdkit
Successfully installed rdkit-2026.3.1

In [2]:
from rdkit import Chem
from rdkit.Chem import Descriptors
import pandas as pd

In [3]:
data = pd.read_csv("valid_smiles.csv")
data

,SMILES,pIC50,mol,num_atoms,logP
0,O=S(=O)(Nc1cccc(-c2cnc3ccccc3n2)c1)c1cccs1,4.26,<rdkit.Chem.rdchem.Mol object at 0x7f59df45bc30>,25,4.15910
1,O=c1cc(-c2nc(-c3ccc(-c4cn(CCP(=O)(O)O)nn4)cc3)...,4.34,<rdkit.Chem.rdchem.Mol object at 0x7f59a320c9e0>,36,3.67430
2,NC(=O)c1ccc2c(c1)nc(C1CCC(O)CC1)n2CCCO,4.53,<rdkit.Chem.rdchem.Mol object at 0x7f59a320cac0>,23,1.53610
3,NCCCn1c(C2CCNCC2)nc2cc(C(N)=O)ccc21,4.56,<rdkit.Chem.rdchem.Mol object at 0x7f59a320cba0>,22,0.95100
4,CNC(=S)Nc1cccc(-c2cnc3ccccc3n2)c1,4.59,<rdkit.Chem.rdchem.Mol object at 0x7f59a320c7b0>,21,3.21300
...,...,...,...,...,...
16062,S=C(NN=C(c1ccccn1)c1ccccn1)Nc1ccccc1,0.00,<rdkit.Chem.rdchem.Mol object at 0x7f59a314ed50>,24,3.21560
16063,S=C=NCCCCCCCCCCc1ccccc1,0.00,<rdkit.Chem.rdchem.Mol object at 0x7f59a314edc0>,19,5.45270
16064,S=C=NCCCCCCCCc1ccccc1,0.00,<rdkit.Chem.rdchem.Mol object at 0x7f59a314ee30>,17,4.67250
16065,S=c1[nH]nc(Cn2ccc3ccccc32)n1-c1ccccc1,0.00,<rdkit.Chem.rdchem.Mol object at 0x7f59a314eea0>,22,3.93289
16066,N=[N+]=NC=Cc1ccc([N+](=O)[O-])o1,0.02,<rdkit.Chem.rdchem.Mol object at 0x7f59a314ef10>,13,1.70887

In [5]:
weight=[]
bonds=[]
tpsa=[]
numhdoner=[]
numhaccept=[]

for i in data["SMILES"]:
  mol = Chem.MolFromSmiles(i)
  weight_value = Descriptors.MolWt(mol)
  atoms_value = mol.GetNumAtoms()
  bonds_value = mol.GetNumBonds()
  tpsa_value = Descriptors.TPSA(mol)
  numhdoner_value = Descriptors.NumHDonors(mol)
  numhaccept_value = Descriptors.NumHAcceptors(mol)
  weight.append(weight_value)
  bonds.append(bonds_value)
  tpsa.append(tpsa_value)
  numhdoner.append(numhdoner_value)
  numhaccept.append(numhaccept_value)


data["Molecular_Weight"] = weight
data["Num_Bonds"] = bonds
data["TPSA"] = tpsa
data["NumHDoner"] = numhdoner
data["NumHAcceptor"] = numhaccept

In [6]:
data

,SMILES,pIC50,mol,num_atoms,logP,Molecular_Weight,Num_Bonds,TPSA,NumHDoner,NumHAcceptor
0,O=S(=O)(Nc1cccc(-c2cnc3ccccc3n2)c1)c1cccs1,4.26,<rdkit.Chem.rdchem.Mol object at 0x7f59df45bc30>,25,4.15910,367.455,28,71.95,1,5
1,O=c1cc(-c2nc(-c3ccc(-c4cn(CCP(=O)(O)O)nn4)cc3)...,4.34,<rdkit.Chem.rdchem.Mol object at 0x7f59a320c9e0>,36,3.67430,506.434,40,149.78,4,5
2,NC(=O)c1ccc2c(c1)nc(C1CCC(O)CC1)n2CCCO,4.53,<rdkit.Chem.rdchem.Mol object at 0x7f59a320cac0>,23,1.53610,317.389,25,101.37,3,4
3,NCCCn1c(C2CCNCC2)nc2cc(C(N)=O)ccc21,4.56,<rdkit.Chem.rdchem.Mol object at 0x7f59a320cba0>,22,0.95100,301.394,24,98.96,3,4
4,CNC(=S)Nc1cccc(-c2cnc3ccccc3n2)c1,4.59,<rdkit.Chem.rdchem.Mol object at 0x7f59a320c7b0>,21,3.21300,294.383,23,49.84,2,3
...,...,...,...,...,...,...,...,...,...,...
16062,S=C(NN=C(c1ccccn1)c1ccccn1)Nc1ccccc1,0.00,<rdkit.Chem.rdchem.Mol object at 0x7f59a314ed50>,24,3.21560,333.420,26,62.20,2,4
16063,S=C=NCCCCCCCCCCc1ccccc1,0.00,<rdkit.Chem.rdchem.Mol object at 0x7f59a314edc0>,19,5.45270,275.461,19,12.36,0,2
16064,S=C=NCCCCCCCCc1ccccc1,0.00,<rdkit.Chem.rdchem.Mol object at 0x7f59a314ee30>,17,4.67250,247.407,17,12.36,0,2
16065,S=c1[nH]nc(Cn2ccc3ccccc32)n1-c1ccccc1,0.00,<rdkit.Chem.rdchem.Mol object at 0x7f59a314eea0>,22,3.93289,306.394,25,38.54,1,2
16066,N=[N+]=NC=Cc1ccc([N+](=O)[O-])o1,0.02,<rdkit.Chem.rdchem.Mol object at 0x7f59a314ef10>,13,1.70887,181.131,13,106.59,1,5

In [7]:
des_values = pd.DataFrame(data)

In [8]:
des_values.to_csv("Descriptors_values.csv",index=False)

In [9]:
df = pd.read_csv("Descriptors_values.csv")
df

,SMILES,pIC50,mol,num_atoms,logP,Molecular_Weight,Num_Bonds,TPSA,NumHDoner,NumHAcceptor
0,O=S(=O)(Nc1cccc(-c2cnc3ccccc3n2)c1)c1cccs1,4.26,<rdkit.Chem.rdchem.Mol object at 0x7f59df45bc30>,25,4.15910,367.455,28,71.95,1,5
1,O=c1cc(-c2nc(-c3ccc(-c4cn(CCP(=O)(O)O)nn4)cc3)...,4.34,<rdkit.Chem.rdchem.Mol object at 0x7f59a320c9e0>,36,3.67430,506.434,40,149.78,4,5
2,NC(=O)c1ccc2c(c1)nc(C1CCC(O)CC1)n2CCCO,4.53,<rdkit.Chem.rdchem.Mol object at 0x7f59a320cac0>,23,1.53610,317.389,25,101.37,3,4
3,NCCCn1c(C2CCNCC2)nc2cc(C(N)=O)ccc21,4.56,<rdkit.Chem.rdchem.Mol object at 0x7f59a320cba0>,22,0.95100,301.394,24,98.96,3,4
4,CNC(=S)Nc1cccc(-c2cnc3ccccc3n2)c1,4.59,<rdkit.Chem.rdchem.Mol object at 0x7f59a320c7b0>,21,3.21300,294.383,23,49.84,2,3
...,...,...,...,...,...,...,...,...,...,...
16062,S=C(NN=C(c1ccccn1)c1ccccn1)Nc1ccccc1,0.00,<rdkit.Chem.rdchem.Mol object at 0x7f59a314ed50>,24,3.21560,333.420,26,62.20,2,4
16063,S=C=NCCCCCCCCCCc1ccccc1,0.00,<rdkit.Chem.rdchem.Mol object at 0x7f59a314edc0>,19,5.45270,275.461,19,12.36,0,2
16064,S=C=NCCCCCCCCc1ccccc1,0.00,<rdkit.Chem.rdchem.Mol object at 0x7f59a314ee30>,17,4.67250,247.407,17,12.36,0,2
16065,S=c1[nH]nc(Cn2ccc3ccccc32)n1-c1ccccc1,0.00,<rdkit.Chem.rdchem.Mol object at 0x7f59a314eea0>,22,3.93289,306.394,25,38.54,1,2
16066,N=[N+]=NC=Cc1ccc([N+](=O)[O-])o1,0.02,<rdkit.Chem.rdchem.Mol object at 0x7f59a314ef10>,13,1.70887,181.131,13,106.59,1,5

In [10]:
df.describe()

,pIC50,num_atoms,logP,Molecular_Weight,Num_Bonds,TPSA,NumHDoner,NumHAcceptor
count,16067.000000,16067.000000,16067.000000,16067.000000,16067.000000,16067.000000,16067.000000,16067.000000
mean,0.999948,18.691666,2.254606,273.131776,19.730192,63.682414,1.229601,3.640319
std,2.398541,8.266598,1.606149,117.383083,9.353073,38.778916,1.203754,2.236686
min,0.000000,3.000000,-5.395600,40.065000,2.000000,0.000000,0.000000,0.000000
25%,0.000000,13.000000,1.213600,186.090500,13.000000,35.530000,0.000000,2.000000
50%,0.020000,17.000000,2.161820,255.026000,18.000000,59.060000,1.000000,3.000000
75%,0.265000,23.000000,3.230000,341.197000,25.000000,88.630000,2.000000,5.000000
max,10.970000,59.000000,10.012900,841.989000,67.000000,267.040000,10.000000,19.000000