In [1]:
!pip install rdkit

Collecting rdkit
  Downloading rdkit-2026.3.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rdkit) (2.0.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from rdkit) (11.3.0)
Downloading rdkit-2026.3.1-cp312-cp312-manylinux_2_28_x86_64.whl (37.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.0/37.0 MB 37.0 MB/s eta 0:00:00
Installing collected packages: rdkit
Successfully installed rdkit-2026.3.1

In [2]:
import pandas as pd
from rdkit import Chem

In [3]:
data = pd.read_csv("clean_data.csv")

In [4]:
data.head()

,SMILES,pIC50,mol,num_atoms,logP
0,O=S(=O)(Nc1cccc(-c2cnc3ccccc3n2)c1)c1cccs1,4.26,<rdkit.Chem.rdchem.Mol object at 0x7f59df45bc30>,25,4.1591
1,O=c1cc(-c2nc(-c3ccc(-c4cn(CCP(=O)(O)O)nn4)cc3)...,4.34,<rdkit.Chem.rdchem.Mol object at 0x7f59a320c9e0>,36,3.6743
2,NC(=O)c1ccc2c(c1)nc(C1CCC(O)CC1)n2CCCO,4.53,<rdkit.Chem.rdchem.Mol object at 0x7f59a320cac0>,23,1.5361
3,NCCCn1c(C2CCNCC2)nc2cc(C(N)=O)ccc21,4.56,<rdkit.Chem.rdchem.Mol object at 0x7f59a320cba0>,22,0.9510
4,CNC(=S)Nc1cccc(-c2cnc3ccccc3n2)c1,4.59,<rdkit.Chem.rdchem.Mol object at 0x7f59a320c7b0>,21,3.2130

In [5]:
data.tail()

,SMILES,pIC50,mol,num_atoms,logP
16062,S=C(NN=C(c1ccccn1)c1ccccn1)Nc1ccccc1,0.00,<rdkit.Chem.rdchem.Mol object at 0x7f59a314ed50>,24,3.21560
16063,S=C=NCCCCCCCCCCc1ccccc1,0.00,<rdkit.Chem.rdchem.Mol object at 0x7f59a314edc0>,19,5.45270
16064,S=C=NCCCCCCCCc1ccccc1,0.00,<rdkit.Chem.rdchem.Mol object at 0x7f59a314ee30>,17,4.67250
16065,S=c1[nH]nc(Cn2ccc3ccccc32)n1-c1ccccc1,0.00,<rdkit.Chem.rdchem.Mol object at 0x7f59a314eea0>,22,3.93289
16066,N=[N+]=NC=Cc1ccc([N+](=O)[O-])o1,0.02,<rdkit.Chem.rdchem.Mol object at 0x7f59a314ef10>,13,1.70887

In [6]:
data.describe()

              pIC50     num_atoms          logP
count  16067.000000  16067.000000  16067.000000
mean       0.999948     18.691666      2.254606
std        2.398541      8.266598      1.606149
min        0.000000      3.000000     -5.395600
25%        0.000000     13.000000      1.213600
50%        0.020000     17.000000      2.161820
75%        0.265000     23.000000      3.230000
max       10.970000     59.000000     10.012900

In [7]:
data.isnull().sum()

SMILES       0
pIC50        0
mol          0
num_atoms    0
logP         0
dtype: int64

In [8]:
data.columns

Index(['SMILES', 'pIC50', 'mol', 'num_atoms', 'logP'], dtype='object')

In [9]:
valid_rows = []

for i, smile in enumerate (data["SMILES"]):
  mol = Chem.MolFromSmiles(smile)
  if mol is None:
    print(smile, "= invalid")
  else:
    print(smile, "= valid")
    valid_rows.append(data.iloc[i])

Streaming output truncated to the last 5000 lines.
Cc1nc([N+](=O)[O-])c(Cl)n1C = valid
Cc1nc(Cl)c([N+](=O)[O-])n1C = valid
CC(C)COC(=O)C=Cc1ccc([N+](=O)[O-])o1 = valid
CN(CC=CC#CC(C)(C)C)Cc1cccc2ccccc12 = valid
CCCCNC(=O)C=Cc1ccc([N+](=O)[O-])o1 = valid
NC(=O)OCCc1c[nH]c2ccccc12 = valid
CCCN(CCC)CCc1cccc2c1CC(=O)N2 = valid
C=CCC1(C(C)(C)C)C(=O)NC(=O)NC1=O = valid
COc1c(OC)c(OC(C)=O)c2cc(Cl)ccc2c1OC(C)=O = valid
O=C(O)CCC1=NS(=O)(=O)c2cc(Br)ccc2N1 = valid
O=C(O)CCC1=NS(=O)(=O)c2cc(Cl)ccc2N1 = valid
CN(C)C(=O)OCCCc1ccccc1 = valid
NC1=NCC(CN2CCN(c3ccccc3)CC2)O1 = valid
CCCCCOC(=O)C=Cc1ccc([N+](=O)[O-])o1 = valid
COc1c(OC)c(OC(=O)C(C)(C)C)c2ccccc2c1OC(=O)C(C)(C)C = valid
COc1c(OC)c(OC(C)=O)c2c(Cl)cccc2c1OC(C)=O = valid
COc1c(OC)c(OC(C)=O)c2cc(F)ccc2c1OC(C)=O = valid
COc1c(OC)c(OC(C)=O)c2cc(Br)ccc2c1OC(C)=O = valid
COc1c(OC)c(OC(C)=O)c2c(OC)cccc2c1OC(C)=O = valid
COc1c(OC)c(OC(C)=O)c2c(C#N)cccc2c1OC(C)=O = valid
COc1c(OC)c(OC(C)=O)c2cc(C#N)ccc2c1OC(C)=O = valid
COc1c(OC)c(OC(C)=O)c2cc(NC(C)=O)ccc2c1OC(C)=O = valid
COc1ccc2c(OC(C)=O)c(OC)c(OC)c(OC(C)=O)c2c1 = valid
COc1c(OC)c(OC(C)=O)c2cc(C)ccc2c1OC(C)=O = valid
CCC(=O)Oc1c(OC)c(OC)c(OC(=O)CC)c2ccccc12 = valid
COc1c(OC)c(OC(=O)C(C)C)c2ccccc2c1OC(=O)C(C)C = valid
CN(C)CCC1CN(C)C(=S)c2cccnc2O1 = valid
N#CC(C#N)=Cc1ccc(Cl)o1 = valid
CCCN(CCc1cccs1)C1CCc2c(O)cccc2C1 = valid
CCNC(=O)c1cc2ccccc2o1 = valid
Clc1ccc2oc3c(Cl)c(Cl)cc(Cl)c3c2c1 = valid
Nc1nc(=O)c2ncn(C3CC(F)C(CO)O3)c2[nH]1 = valid
CCC(C(=O)OC(C)c1ccccc1)C(CO)Cc1cncn1C = valid
CCC(C(=O)OCc1ccccc1)C(CO)Cc1cncn1C = valid
CCC(C(=O)OCc1ccccc1)C(COC(=O)c1ccccc1)Cc1cncn1C = valid
CCC(C(=O)OCCc1ccccc1)C(CO)Cc1cncn1C = valid
CCC(C(=O)OCc1ccc(Cl)cc1)C(CO)Cc1cncn1C = valid
CCC(C(=O)OCc1ccc(Cl)cc1)C(COC(=O)c1ccccc1)Cc1cncn1C = valid
CCC(C(=O)OCc1ccccc1C)C(CO)Cc1cncn1C = valid
CCC(C(=O)OCc1ccc(C)cc1)C(CO)Cc1cncn1C = valid
CCC(C(=O)OCc1ccc(C)cc1)C(COC(=O)c1ccccc1)Cc1cncn1C = valid
CCC(C(=O)OCc1ccc(C(C)(C)C)cc1)C(CO)Cc1cncn1C = valid
CCC(C(=O)OCc1ccccc1)C(COC(=O)Cc1ccccc1)Cc1cncn1C = valid
CCC(C(=O)OCc1ccccc1)C(COC(=O)c1cccc(Cl)c1)Cc1cncn1C = valid
CCN(CC)C(=O)C1(c2ccccc2)CC1CN = valid
CCC(C(=O)OCc1ccccc1)C(COC(=O)c1cccnc1)Cc1cncn1C = valid
CCCCCCCc1nn[nH]n1 = valid
C#CC1(O)C(F)CC2C3CCc4cc(O)ccc4C3CCC21C = valid
CN(C(=O)C(Cl)Cl)c1ccc(OC(=O)c2ccccc2)cc1 = valid
c1ccc(C2=NOC3COC(c4ccccc4)OCC23)cc1 = valid
CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C1(O)C(=O)COC1OC(CO)C(O)C(O)C1O = valid
CC12CCC(=O)C=C1CCC1C2C(O)CC2(C)C1CCC2(O)C(=O)COC1OC(CO)C(O)C(O)C1O = valid
CC12C=CC(=O)C=C1CCC1C2C(O)CC2(C)C1CCC2(O)C(=O)COC1OC(CO)C(OC2OC(CO)C(O)C(O)C2O)C(O)C1O = valid
CNC(C)C(OC)c1ccccc1 = valid
COc1cc(S(C)=O)ccc1-c1cn2cccnc2n1 = valid
CCCC(O)C(C(=O)O)c1ccc(-c2ccccc2)cc1 = valid
O=C(O)C(c1ccc(-c2ccccc2)cc1)C(O)c1ccccc1 = valid
COc1cccc(C(O)C(C(=O)O)c2ccc(-c3ccccc3)cc2)c1 = valid
COc1ccc(C(O)C(C(=O)O)c2ccc(-c3ccccc3)cc2)cc1 = valid
O=C(O)C(c1ccc(-c2ccccc2)cc1)C(O)c1ccccc1F = valid
O=C(O)C(c1ccc(-c2ccccc2)cc1)C(O)c1cccc(F)c1 = valid
CC(C)(O)C(C(=O)O)c1ccc(-c2ccccc2)cc1 = valid
CC(C)C(O)C(C(=O)O)c1ccc(-c2ccccc2)cc1 = valid
COc1ccccc1C=CC(=O)OCCOc1ccc(C=O)cc1OC = valid
COc1cc(C=O)ccc1OCCOC(=O)c1ccccc1Cl = valid
COc1cc(C=O)ccc1OCCOC(=O)c1cccc(Cl)c1 = valid
COc1cc(C=O)ccc1OCCOC(=O)c1ccc(Cl)cc1 = valid
COc1cc(CN=O)ccc1OCCOC(=O)c1ccc(Cl)cc1 = valid
COc1cc(CN=O)ccc1OCCOC(=O)c1cccc(Cl)c1 = valid
COc1cc(CN=O)ccc1OCCO = valid
CCOC(=O)CON=Cc1ccc(OCCOC(=O)c2cc(OC)c(OC)c(OC)c2)c(OC)c1 = valid
C=CCN1CCC(CNC(=O)c2cc3nn[nH]c3cc2OC)C1 = valid
CCN(CC)CCNC(=O)c1cc(F)c(N)cc1OC = valid
CCN(CC)CCNC(=O)c1cc(I)c(N)cc1OC = valid
CCN1CCC(CNC(=O)c2cc(S(N)(=O)=O)ccc2OC)C1 = valid
CCN1CCC(CNC(=O)c2cc(S(=O)(=O)CC)ccc2OC)C1 = valid
CCN1CCC(CNC(=O)c2cc(S(N)(=O)=O)c(N)cc2OC)C1 = valid
CCN(CC)CCNC(=O)c1cc(S(=O)(=O)CC)c(N)cc1OC = valid
CCCCCOCc1ccccc1NC(=O)OCCN1CCCCC1 = valid
CCCCOCc1cccc(NC(=O)OCCN2CCCCC2)c1 = valid
CCCCCOCc1cccc(NC(=O)OCCN2CCCCC2)c1 = valid
CCCCOCc1ccccc1NC(=O)OCCN1CCCCC1 = valid
Cc1cccc(N2C(=O)CCC2=O)c1 = valid
CCCCCCC(C)=NNC(=N)N = valid
CCN(CC)C(=O)OCC(C)C = valid
CCOC(=O)c1cnn(C)c1S(=O)(=O)NC(=O)Nc1nc(OC)cc(OC)n1 = valid
N#Cc1cc(-c2ccccc2)nnc1NCCN1CCOCC1 = valid
O=C(NC(=O)c1c(F)cccc1F)Nc1ccc(CON=C(c2ccc(Cl)cc2)C2CC2)cc1 = valid
Cc1nccnc1OC(C)C = valid
C=C(C)CC(C)(CCC=C(C)C)OC(C)=O = valid
Clc1ccc(Oc2cc(Cl)c(Cl)c(Cl)c2)cc1Cl = valid
Clc1cc(Oc2ccc(Cl)c(Cl)c2Cl)cc(Cl)c1Cl = valid
CC(C1CC1)C(O)(Cn1cncn1)c1ccc(Cl)cc1 = valid
CCCC(=O)n1c(=O)[nH]cc(F)c1=O = valid
CC1(C)Oc2ccc(C#N)cc2C(N2CCCC2=O)C1O = valid
COC(=O)Nc1nonc1C = valid
COCC(=O)Nc1ccc(Cl)c(Cl)c1 = valid
COC(=O)Nc1ccc(C#N)cc1 = valid
COCCOc1ccccc1S(=O)(=O)N=C(O)N=c1nc(OC)[nH]c(OC)n1 = valid
NS(=O)(=O)c1nc2ccc([N+](=O)[O-])cc2s1 = valid
Nc1ccc2nc(S(N)(=O)=O)sc2c1 = valid
CCc1ccc(C=CC(C)=O)cc1 = valid
C=CCC1(C2=CCCC2)C(=O)NC(=O)N(C)C1=O = valid
COc1ccnc(C#N)n1 = valid
CCCN1CCOC2c3cccc(O)c3CCC21 = valid
C=COC(=O)C(C)Oc1cc(Oc2ccc(C(F)(F)F)cc2Cl)ccc1[N+](=O)[O-] = valid
CCNC(=O)Cn1cccc(O)c1=O = valid
CNC(=O)Cn1cccc(O)c1=O = valid
CCCNC(=O)Cn1cccc(O)c1=O = valid
CC(C)NC(=O)Cn1cccc(O)c1=O = valid
CCCCNC(=O)Cn1cccc(O)c1=O = valid
Cc1c(O)c(=O)ccn1CCCCO = valid
CCOc1ccc(NC(=O)OCC(C)C)cc1OCC = valid
CCOc1ccc(NC(=O)OCCOC)cc1OCC = valid
CCOc1ccc(NC(=O)OCc2ccccc2)cc1OCC = valid
CCOC(=O)C1CC(=O)C(=C(O)C2CC2)C(=O)C1 = valid
Oc1ccc(Cn2cc[nH]c2=S)cc1F = valid
Oc1c(F)cc(Cn2cc[nH]c2=S)cc1F = valid
Oc1ccc(Cn2cc[nH]c2=S)cc1 = valid
Fc1ccccc1Cn1cc[nH]c1=S = valid
Fc1cc(F)cc(Cn2cc[nH]c2=S)c1 = valid
O=C(Cc1ccccc1)Nc1cccc(I)c1 = valid
CNc1cccc(NC(=O)Cc2ccccc2)c1 = valid
CCNc1cccc(NC(=O)Cc2ccccc2)c1 = valid
CC(=O)Oc1cccc(NC(=O)Cc2ccccc2)c1 = valid
CS(=O)(=O)Oc1cccc(NC(=O)Cc2ccccc2)c1 = valid
O=C(Cc1ccccc1)Nc1ccc(O)cc1 = valid
O=C(Cc1ccccc1)Nc1ccccc1O = valid
Nc1ccccc1NC(=O)Cc1ccccc1 = valid
COc1ccccc1NC(=O)Cc1ccccc1 = valid
CC(=O)OC1(C(=O)CO)CCC2C3CCC4=CC(=O)C=CC4(C)C3C(=O)CC21C = valid
O=[N+]([O-])c1ccc(C=CS(=O)(=O)c2ccccc2)o1 = valid
CCOP(=O)(SC(C)CC)SC(C)CC = valid
COc1cc2nc(N3CCN(C(=O)C(C)OC)CC3)nc(N)c2cc1OC = valid
COc1noc2c1CNCC2 = valid
COc1noc2c1CN(C)CC2 = valid
NS(=O)(=O)c1nc2ccc(OCCO)cc2s1 = valid
CC(=O)Nc1cc([N+](=O)[O-])c(Br)cc1F = valid
CCN(CC)C(=O)CC1CCCCC1 = valid
CCC(=O)OC1(C(=O)CCl)C(C)CC2C3CCC4=CC(=O)C=CC4(C)C3C(O)CC21C = valid
CCC(=O)OC1(C(=O)CCl)C(C)CC2C3CCC4=CC(=O)C=CC4(C)C3C(=O)CC21C = valid
CC(CCO)C(F)(F)F = valid
CCCN(CCC)C1CCc2c(OC)cccc2C1C = valid
COC1=CC(=O)c2c(c(COC(N)=O)c3n2CCC3OC(C)=O)C1=O = valid
CNC(=O)OCc1c2c(n3c1C(OC(C)=O)CC3)C(=O)C=C(OC)C2=O = valid
CNC(=O)OCc1c2c(n3c1C(OC(C)=O)CC3)C(=O)C(Cl)=C(OC)C2=O = valid
CNC(=O)OCc1c2c(n3c1C(OC(C)=O)CC3)C(=O)C(C)=C(OC)C2=O = valid
CNC(=O)OCc1c2c(n3c1C(OC(C)=O)CC3)C(=O)C=C(N1CCCC1)C2=O = valid
O=C(OCCNC(=O)C(F)(F)F)c1ccccc1 = valid
COc1ccc(C=CC(=O)C(F)(F)F)cc1 = valid
NC(=O)c1c(Br)cccc1Br = valid
CCOC(=O)Cn1cnc([N+](=O)[O-])c1I = valid
CCOC(=O)Cn1cnc(I)c1[N+](=O)[O-] = valid
O=C(Cc1nc(I)c([N+](=O)[O-])[nH]1)NCc1cccnc1 = valid
Cc1cccc(C(=O)c2ccc3n2CCC3C(=O)O)c1 = valid
O=CC1=CC=C2C(C(=O)O)CCN2c2cc(Br)ccc21 = valid
CC(C)Oc1ccc(C(=O)c2ccc3n2CCC3C(=O)O)cc1 = valid
C=CCOc1ccc(C(=O)c2ccc3n2CCC3C(=O)O)cc1 = valid
O=C(c1cccc(C(F)(F)F)c1)c1ccc2n1CCC2C(=O)O = valid
O=C(c1ccc(C(F)(F)F)cc1)c1ccc2n1CCC2C(=O)O = valid
O=C(c1c(F)cccc1F)c1ccc2n1CCC2C(=O)O = valid
O=C(c1ccc(F)cc1F)c1ccc2n1CCC2C(=O)O = valid
O=C(c1ccc(Cl)cc1Cl)c1ccc2n1CCC2C(=O)O = valid
O=C(c1c(F)c(F)c(F)c(F)c1F)c1ccc2n1CCC2C(=O)O = valid
O=C(c1ccc(-c2ccccc2)cc1)c1ccc2n1CCC2C(=O)O = valid
O=C(c1ccc2n1CCC2C(=O)O)C1CCC1 = valid
O=C(Cc1ccccc1)c1ccc2n1CCC2C(=O)O = valid
N#CC(C#N)=NNc1cccc(O)c1 = valid
CCCn1c(=O)c2nc(-c3ccccc3N)[nH]c2n(CCC)c1=O = valid
CC(=O)n1ncc2c(O)ncnc21 = valid
CCC(=O)n1ncc2c(O)ncnc21 = valid
O=C(c1ccccc1)n1ncc2c(=O)[nH]cnc21 = valid
Cn1nnnc1SCC1=C(C(=O)OCOC(=O)C(C)(C)C)N2C(=O)C(NC(=O)Cc3csc(N)n3)C2SC1 = valid
CC(C)(C)C(=O)OCOC(=O)C1=C(CSc2nncs2)CSC2C(NC(=O)Cn3cnnn3)C(=O)N12 = valid
CCCC(=O)n1ncc2c(O)ncnc21 = valid
Cc1nnc(SCC2=C(C(=O)OCOC(=O)C(C)(C)C)N3C(=O)C(NC(=O)Cn4cnnn4)C3SC2)s1 = valid
NS(=O)(=O)c1nc2c(Cl)cc(Cl)cc2s1 = valid
NS(=O)(=O)c1nc2ccc(OCc3ccccc3)cc2s1 = valid
CC(=O)Nc1ccc2nc(S(N)(=O)=O)sc2c1 = valid
CC(C)(C)c1ccc(CSc2cnn(C(C)(C)C)c(=O)c2Cl)cc1 = valid
COc1ccsc1CN(C(=O)CCl)c1c(C)cccc1C = valid
CC1(C)CC(NC(=O)NP(=O)(N2CC2)N2CC2)CC(C)(C)N1O = valid
CC1(C)CC(NC(=O)NP(=O)(N2CC2)N2CC2)CC(C)(C)N1 = valid
CCCCCCCCCCCCCc1ccccc1O = valid
CC(=NNC(=S)NNC(=S)N(C)C)c1ccccn1 = valid
CCOC(=O)CC(CO)C(CC)c1cncn1C = valid
CCCCCCOC(=O)C(CC)C(CO)Cc1cncn1C = valid
CCc1cccc(C)c1NC(C)=O = valid
Cc1ccc(S(N)(=O)=O)c(NC(=O)C(C)C)c1 = valid
CC(C)C(=O)Nc1cc(C(F)(F)F)ccc1S(N)(=O)=O = valid
COc1ccc(S(N)(=O)=O)c(NC(=O)C(C)C)c1 = valid
CCC(CC)C(=O)Nc1cc(C)ccc1S(N)(=O)=O = valid
CCC(CC)C(=O)Nc1cc(C(F)(F)F)ccc1S(N)(=O)=O = valid
CCC(CC)C(=O)Nc1cc(OC)ccc1S(N)(=O)=O = valid
CC(=NNC(N)=Nc1ccccc1)c1ccccc1 = valid
CCCC(CCC)=NNC(N)=Nc1ccccc1 = valid
CCCCC(C)=NNC(N)=Nc1ccccc1 = valid
N=C(N)NN=C(c1ccccc1)c1cccs1 = valid
CCCC(CCC)=NNC(=N)N = valid
N=C(N)NN=Cc1cccs1 = valid
COC(=O)C1(S(=O)(=O)c2ccccc2)CC1 = valid
C=CCNC(=O)CN(CC=C)C(=O)C(Cl)Cl = valid
CCC(C)OC(=O)C=Cc1ccc([N+](=O)[O-])o1 = valid
CC(C)(C)OC(=O)C=Cc1ccc([N+](=O)[O-])o1 = valid
CCC(C)NC(=O)C=Cc1ccc([N+](=O)[O-])o1 = valid
CC(C)(C)CNC(=O)C=Cc1ccc([N+](=O)[O-])o1 = valid
COC(=O)C(=Cc1ccc(C)o1)[N+](=O)[O-] = valid
O=C1NC(=S)NC(=O)C1C(=O)Nc1ccccc1 = valid
O=C(O)c1ccc(Cl)cc1Nc1cccc(Br)c1 = valid
CCOc1nc(NC)nc(NC(=O)NS(=O)(=O)c2ccccc2C(=O)OC)n1 = valid
CCC(C)NC(=O)C=C(Br)c1ccccc1 = valid
CCC(C)NC(=O)C=C(Cl)c1ccccc1 = valid
CCC(C)NC(=O)C=Cc1ccccc1 = valid
CCC(C)NC(=O)C=C(SC)c1ccccc1 = valid
CCC(C)NC(=O)C(=Cc1ccccc1)Sc1ccccc1 = valid
CCC(C)NC(=O)C=C(N)c1ccc(Cl)cc1 = valid
CCOCCOC(=O)C(C#N)=C(CC)NCc1ccc([N+](=O)[O-])cc1 = valid
CSC(=O)c1c(C(F)F)nc(C(F)(F)F)c(C(=O)SC)c1CC(C)C = valid
Cc1cnc(C#N)cn1 = valid
CCn1cc(C(=O)O)c(=O)c2cc(F)c(N3CCNC(C)C3)cc21 = valid
CCn1cc(C(=O)O)c(=O)c2cc(F)c(N3CCNC(C)C3)c(F)c21 = valid
Nc1nc(-c2ccnc(NCCCc3ccccc3)c2)n[nH]1 = valid
CN1CCN(c2cc3c(cc2F)c(=O)c(C(=O)O)cn3-c2ccc(F)cc2)CC1 = valid
CC(Cc1ccccc1)OC(=O)N(C)C = valid
CN(C)C(=O)OCCc1c[nH]c2ccccc12 = valid
CCN(CC)C(=O)OCCc1c[nH]c2ccccc12 = valid
NC(=O)OCCCc1cccnc1 = valid
CN(C)C(=O)OCCCc1cccnc1 = valid
CCN(CC)C(=O)OCCCc1ccccn1 = valid
CCC(CC)COC(=O)N(C)C = valid
CCC(CC)COC(=O)N(CC)CC = valid
CN(C)C(=O)OCCc1ccccc1 = valid
CCN(CC)C(=O)OCCc1ccccc1 = valid
NC(C(=O)OCn1ncc2c(=O)[nH]cnc21)c1ccccc1 = valid
NC(Cc1ccccc1)C(=O)OCn1ncc2c(=O)[nH]cnc21 = valid
CC(C)CC(N)C(=O)OCn1ncc2c(=O)[nH]cnc21 = valid
CCN(CC)CC(=O)OCn1ncc2c(=O)[nH]cnc21 = valid
CCCN(CCC)CC(=O)OCn1ncc2c(=O)[nH]cnc21 = valid
CCN(CC)C(C)C(=O)OCn1ncc2c(=O)[nH]cnc21 = valid
COC(=O)c1[nH]cc(-c2ccc(Cl)cc2)c1N1CCOCC1 = valid
CCN(CC)CCCN=c1cc2n(-c3ccc(Cl)cc3)c3ccccc3nc-2cc1Nc1ccc(Cl)cc1 = valid
CC(C)(C)NC(=O)C1CCC2C3CCC4NC(=O)C=CC4(C)C3CCC12C = valid
O=c1ccc(C=Cc2ccc(-n3ccnc3)cc2)n[nH]1 = valid
O=c1ccc(C=Cc2ccc(-n3cnc4c3CCCC4)cc2)n[nH]1 = valid
Cc1cc(=O)[nH]nc1C=Cc1ccc(-n2ccnc2)cc1 = valid
O=C1CC(Sc2ccccc2C(=O)OCc2ccccc2)N1 = valid
CCCCCCNC(=O)c1ccc(O)c(O)c1 = valid
CC(=O)c1c(C)no[n+]1[O-] = valid
CC(=O)c1no[n+]([O-])c1C = valid
CCCN(C(C)=O)C(C)C = valid
CCNC(=O)c1cccs1 = valid
CC1COc2ccccc2N1C(=O)C(Cl)Cl = valid
COc1cccc(CN(C)N=O)c1 = valid
CN(Cc1cccc(Cl)c1)N=O = valid
CN(Cc1cccc(Br)c1)N=O = valid
CN(Cc1cccc(C(F)(F)F)c1)N=O = valid
CN(Cc1ccc(Br)cc1)N=O = valid
COC(=O)c1ccc(CN(C)N=O)cc1 = valid
CN(Cc1cccc([N+](=O)[O-])c1)N=O = valid
CC(C)(C)C(=O)OCn1cc2c(=O)[nH]cnc2n1 = valid
CC(C)(C)C(=O)OCn1cnc2c(cnn2COC(=O)C(C)(C)C)c1=O = valid
CC(C)(C)C(=O)OCn1cc2c(=O)n(COC(=O)C(C)(C)C)cnc2n1 = valid
CC(C)(C)C(=O)OCn1ncc2c(O)ncnc21 = valid
CCCC(=O)OCn1cnc2c(cnn2COC(=O)CCC)c1=O = valid
CCCC(=O)OCn1cc2c(=O)n(COC(=O)CCC)cnc2n1 = valid
CCCC(=O)OCn1ncc2c(=O)[nH]cnc21 = valid
CCCC(=O)OCn1cc2c(=O)[nH]cnc2n1 = valid
CCOC(=O)OCn1ncc2c(O)ncnc21 = valid
CCN(CC)C(=O)CCC(=O)OCn1ncc2c(O)ncnc21 = valid
CC(=O)OCn1ncc2c(O)ncnc21 = valid
O=C(OCn1ncc2c(=O)[nH]cnc21)c1ccccc1 = valid
O=C(OCn1ncc2c(=O)[nH]cnc21)c1cccnc1 = valid
CCOP(=O)(SC(C)CC)N1CCSC1=O = valid
Cc1[nH]cnc1CSCCNC1=NC(=O)CN1 = valid
Cc1[nH]cnc1CSCCNc1[nH]ccc(=O)c1[N+](=O)[O-] = valid
CNc1c(NCCSCc2nc[nH]c2C)c(=O)c1=O = valid
CC(C)c1ccc(C=[N+]([O-])c2ccccc2)cc1 = valid
CCCC1(CCC)C(=O)NC(=S)NC1=O = valid
CC(C)C1(C(C)C)C(=O)NC(=O)NC1=O = valid
COc1ccc(C(CN(C)C)C2(O)CCCCC2)cc1 = valid
CC(=O)Nc1ccc(Cl)c(Cl)c1Cl = valid
COc1ccc(C(=O)CC(C)CC(=O)O)cc1Cl = valid
CCCSC(N=O)C(=O)c1ccc(Br)cc1 = valid
COC(=O)C1=C(C)NC(C)=C(C(=O)OCC=Cc2ccccc2)C1c1cccc([N+](=O)[O-])c1 = valid
CCCCCC(C)OC(=O)COc1ccc(Cl)c2cccnc12 = valid
CCn1cc(C(=O)O)c(=O)c2cc(F)c(N3CCNCC3)c(F)c21 = valid
CC(C)(C)c1noc(CN=O)n1 = valid
CC(=O)Oc1ccc(N(C)C(=O)C(Cl)Cl)cc1 = valid
CC(O)COC(=O)C(N)Cc1ccc(O)c(O)c1 = valid
COCC(C)OC(=O)C(N)Cc1ccc(O)c(O)c1 = valid
NC(Cc1ccc(O)c(O)c1)C(=O)OC1CCCCC1 = valid
NC(Cc1ccc(O)c(O)c1)C(=O)OCC1CCCCO1 = valid
NC(Cc1ccc(O)c(O)c1)C(=O)OCCc1ccccc1 = valid
NC(Cc1ccc(O)c(O)c1)C(=O)OCCc1ccc(Cl)cc1 = valid
COc1ccc(CCOC(=O)C(N)Cc2ccc(O)c(O)c2)cc1 = valid
NC(Cc1ccc(O)c(O)c1)C(=O)OCCOc1ccccc1 = valid
CCCNC(=O)c1cc2ccccc2[nH]1 = valid
OC1(c2ccc(Cl)cc2)CCCCCC1n1cncn1 = valid
OC1(c2ccccc2Cl)CCCCC1n1cncn1 = valid
OC1(c2cc(Cl)ccc2Cl)CCCCC1n1cncn1 = valid
CCCCCCC(=O)N1CCCC1=O = valid
CCOc1cc(Cc2cnc(N)nc2N)cc(OCC)c1 = valid
COc1ccccc1N1CCN(CCNC(=O)C2CCCCC2)CC1 = valid
O=C(C=Cc1ccc(O)c(O)c1)NCc1ccccc1 = valid
CCCCCCNC(=O)C=Cc1ccc(O)c(O)c1 = valid
CCCCC=Cc1ccc(O)c(O)c1 = valid
O=C(O)Cc1ccccc1Nc1c(F)cccc1Cl = valid
COC(=O)c1c(Cl)nn(C)c1S(=O)(=O)NC(=O)Nc1nc(OC)cc(OC)n1 = valid
O=P(NN=Cc1ccc(Cl)cc1)(N1CC1)N1CC1 = valid
O=P(NN=Cc1ccccc1)(N1CC1)N1CC1 = valid
COc1ccc(C=NNP(=O)(N2CC2)N2CC2)cc1 = valid
O=[N+]([O-])c1ccc(C=NNP(=O)(N2CC2)N2CC2)cc1 = valid
CN(N=Cc1ccccc1)P(=O)(N1CC1)N1CC1 = valid
CN(N=Cc1ccc(F)cc1)P(=O)(N1CC1)N1CC1 = valid
CN(N=Cc1ccc(Br)cc1)P(=O)(N1CC1)N1CC1 = valid
COc1ccc(C=NN(C)P(=O)(N2CC2)N2CC2)cc1 = valid
CN(N=Cc1ccc([N+](=O)[O-])cc1)P(=O)(N1CC1)N1CC1 = valid
O=P(N1CC1)(N1CC1)N(N=Cc1ccccc1)c1ccccc1 = valid
O=P(N1CC1)(N1CC1)N(N=Cc1ccc(F)cc1)c1ccccc1 = valid
COc1ccc(C=NN(c2ccccc2)P(=O)(N2CC2)N2CC2)cc1 = valid
O=[N+]([O-])c1ccc(C=NN(c2ccccc2)P(=O)(N2CC2)N2CC2)cc1 = valid
O=[N+]([O-])c1ccc(N(N=Cc2ccccc2)P(=O)(N2CC2)N2CC2)cc1 = valid
CC(C)=NNP(=O)(N1CC1)N1CC1 = valid
CC(C)=NN(C)P(=O)(N1CC1)N1CC1 = valid
CC(C)=NN(c1ccccc1)P(=O)(N1CC1)N1CC1 = valid
O=P(N1CC1)(N1CC1)N(N=Cc1ccc(Cl)cc1)c1ccccc1 = valid
O=P(NN=Cc1ccc(F)cc1)(N1CC1)N1CC1 = valid
CC(=O)c1ccc(S(=O)(=O)c2ccc(N)cc2)cc1 = valid
N#Cc1ccc(C=CC(=O)C(F)(F)F)cc1 = valid
N#Cc1cccc(C=CC(=O)C(F)(F)F)c1 = valid
CC(O)CC(F)(F)F = valid
O=C(O)CCC1=NS(=O)(=O)c2ccc(Cl)cc2N1 = valid
O=C(O)CCC1=NS(=O)(=O)c2cc(Cl)cc(Cl)c2N1 = valid
O=C(O)CCC1=NS(=O)(=O)c2cc(Cl)c(Cl)cc2N1 = valid
O=C(O)CCC1=NS(=O)(=O)c2cc(Br)cc(Br)c2N1 = valid
Cc1ccc2c(c1)NC(CCC(=O)O)=NS2(=O)=O = valid
COc1ccc2c(c1)NC(CCC(=O)O)=NS2(=O)=O = valid
O=C(O)CCC1=NS(=O)(=O)c2ccc(C(F)(F)F)cc2N1 = valid
O=C(O)CCCC1=NS(=O)(=O)c2ccc(Cl)cc2N1 = valid
O=C(O)CCCC1=NS(=O)(=O)c2cc(Cl)ccc2N1 = valid
O=C(O)CCCC1=NS(=O)(=O)c2cc(Cl)cc(Cl)c2N1 = valid
O=C(O)CCCC1=NS(=O)(=O)c2cc(Cl)c(Cl)cc2N1 = valid
O=C(O)CCCC1=NS(=O)(=O)c2cc(Br)ccc2N1 = valid
O=C(O)CCCC1=NS(=O)(=O)c2cc(Br)cc(Br)c2N1 = valid
Cc1ccc2c(c1)NC(CCCC(=O)O)=NS2(=O)=O = valid
COc1ccc2c(c1)NC(CCCC(=O)O)=NS2(=O)=O = valid
O=C(O)CCCC1=NS(=O)(=O)c2ccc(C(F)(F)F)cc2N1 = valid
Cc1cccc(Cl)c1C(N)=O = valid
Cc1cc(OCCN(C)C)c(C(C)C)cc1OC1CCCCC1=O = valid
Cc1cc(OCCNCC2CC(=O)c3ccccc3C2=O)c(C(C)C)cc1O = valid
CC(=O)Oc1ccc(OCCN(C)C)cc1C = valid
CNc1ncnc2c1ncn2Cc1ccccc1F = valid
CN=C(NC)N[N+](=O)[O-] = valid
CCOCCOCCOP(=O)(N1CC1)N1CC1 = valid
CCOCCOCCOP(=S)(N1CC1)N1CC1 = valid
N#CC(C#N)=NNc1ccccc1Br = valid
N#CC(C#N)=NNc1ccccc1C(F)(F)F = valid
Cc1ccc(C)c(NN=C(C#N)C#N)c1 = valid
C=CC(=O)NCCCN(CCO)CCO = valid
N#Cc1ccc(S(=O)(=O)c2ccc(N)cc2)cc1 = valid
CCN(CC)C(=O)c1ccc(S(=O)(=O)c2ccc(N)cc2)cc1 = valid
C=CCN1CCc2nc(N)sc2CC1 = valid
O=C(O)CCCCOc1cccc2ccccc12 = valid
O=C(O)CCCCCOc1cccc2ccccc12 = valid
O=C1CCC(c2ccc[n+]([O-])c2)N1 = valid
NC(=O)c1ccccc1NCC(O)CO = valid
CC(O)CNc1ccccc1C(N)=O = valid
CCCCOCCNc1ccccc1C(N)=O = valid
CCCCOCCNc1ccc(Cl)cc1C(N)=O = valid
Cc1ccccc1OCCNc1ccccc1C(N)=O = valid
NC(=O)c1cc(Cl)ccc1NCCO = valid
CCCOc1ccccn1 = valid
CCCCCCCCCCCCN1CC(C(=O)OC)CC1=O = valid
C=CCCCOC(=O)C(CC)N(Cc1ccco1)C(=O)n1ccnc1 = valid
Cc1cccc(C)c1NC(=O)CCCN = valid
Cc1cccc(C)c1NC(=O)CCCCN = valid
Cc1cccc(C)c1NC(=O)CCCCCN = valid
Cc1cccc(C)c1NC(=O)CCC(C)N = valid
CCN(CC)CCCCCC(=O)Nc1c(C)cccc1C = valid
COC(=O)C1=C(C)NC(C)=C(P2(=O)OCCCO2)C1c1ccccc1[N+](=O)[O-] = valid
CCCNCC(O)COc1ccc(-c2ncc(-c3cccs3)[nH]2)cc1 = valid
CCOCCNCC(O)COc1ccc(-c2ncc(-c3cccs3)[nH]2)cc1 = valid
OC(CNCCc1ccncc1)COc1ccc(-c2ncc(-c3cccs3)[nH]2)cc1 = valid
CCCCNC(=O)NCCNCC(O)COc1ccc(-c2ncc(C)[nH]2)cc1 = valid
COc1ccc(CCNCC(O)COc2ccc(COCc3ncc[nH]3)cc2)cc1OC = valid
COc1ccc(CCNCC(O)COc2ccc(-c3ncc(C)[nH]3)cc2OC)cc1OC = valid
COc1ccc(CCNCC(O)COc2ccc(-c3nc(C(C)=O)c(C)[nH]3)cc2)cc1OC = valid
COCCc1cnc(-c2ccc(OCC(O)CNCCc3ccc(OC)c(OC)c3)cc2)[nH]1 = valid
COc1ccc(CCNCC(O)COc2ccc(-c3ncc(Cl)[nH]3)cc2)cc1OC = valid
CCOC(=O)c1cnc(-c2ccc(OCC(O)CNCCc3ccc(OC)c(OC)c3)cc2)[nH]1 = valid
N=c1cc2n(-c3ccc(Cl)cc3)c3ccccc3nc-2cc1Nc1ccc(Cl)cc1 = valid
CC(=O)OCOc1ccccc1C(=O)NCN1CCOCC1 = valid
CCCC(=O)OCOc1ccccc1C(=O)NCN1CCOCC1 = valid
CC(C)(C)C(=O)OCOc1ccccc1C(=O)NCN1CCOCC1 = valid
CC(=O)OCOc1ccccc1C(N)=O = valid
COCc1cnc(-c2ccc(OCC(O)CNCCc3ccc(OC)c(OC)c3)cc2)[nH]1 = valid
COc1cc(S(C)=O)ccc1-c1cn2ccnc(OC)c2n1 = valid
COc1cc(C(N)=O)ccc1-c1cn2cccnc2n1 = valid
COc1cc(S(C)=O)ccc1-c1cn2ccncc2n1 = valid
CNc1nccn2cc(-c3ccc(S(C)=O)cc3OC)nc12 = valid
CNc1nc2c3cccnc3ccc2n1C = valid
CN(C)c1nc2c3cccnc3ccc2n1C = valid
Cc1ccccc1C1=CCN(C)CC1 = valid
CN(C)C(=O)Nc1cccc(Cc2ccccc2)c1 = valid
CN(C)C(=O)Nc1cccc(CCc2ccccc2)c1 = valid
CCNc1nc(Cl)nc(NC2CCC2)n1 = valid
CCCCCC(C)Nc1nc(Cl)nc(NCC)n1 = valid
CNC(=O)Nc1nonc1C = valid
N=C(N)NN=Cc1ccc(Cl)c([N+](=O)[O-])c1 = valid
N=C(N)NN=Cc1ccccc1[N+](=O)[O-] = valid
CN(C)C(N(C)C)=S(I)c1ccccc1F = valid
CN(C)C(N(C)C)=S(I)c1cccc(F)c1 = valid
CN(C)C(N(C)C)=S(I)c1ccccc1Cl = valid
CN(C)C(N(C)C)=S(I)c1cccc(Cl)c1 = valid
CN(C)C(N(C)C)=S(I)c1ccccc1Br = valid
CN(C)C(N(C)C)=S(I)c1cccc(Br)c1 = valid
CN(C)C(N(C)C)=S(I)c1ccccc1I = valid
CN(C)C(N(C)C)=S(I)c1cccc(I)c1 = valid
CN(C)C(N(C)C)=S(I)c1ccc(I)cc1 = valid
CN(C)C(N(C)C)=S(I)c1ccc(Cl)c(Cl)c1 = valid
CN(C)C(N(C)C)=S(I)c1cc(Cl)ccc1Cl = valid
CN(C)C(N(C)C)=S(I)c1cc(Cl)c(Cl)cc1Cl = valid
Cc1ccc(S(I)=C(N(C)C)N(C)C)cc1Cl = valid
O=C(NC(=O)c1c(F)cccc1F)Nc1cc(Cl)c(OC(F)(F)C(F)C(F)(F)F)cc1Cl = valid
O=C1C2C3C=CC(C3)C2C(=O)N1CCCCN1CCN(c2ncccn2)CC1 = valid
O=C(C=Cc1ccc(O)c(O)c1)NCCc1ccccc1 = valid
COc1ccc(I)cc1Cc1cnc(N)nc1N = valid
C#CCN1C(=O)COc2cc(F)c(N3C(=O)C4=C(CCCC4)C3=O)cc21 = valid
Clc1cc2c(Cl)cc(Cl)c(Cl)c2c(Cl)c1Cl = valid
Clc1cc2c(Cl)c(Cl)c(Cl)c(Cl)c2cc1Cl = valid
COCN(C#N)C1CC(OC2CC(O)(C(C)=O)Cc3c(O)c4c(c(O)c32)C(=O)c2c(OC)cccc2C4=O)OC(C)C1O = valid
O=NCc1nc(-c2cccs2)no1 = valid
O=NCc1nc(Cc2ccccc2)no1 = valid
O=NCc1noc(-c2ccccc2)n1 = valid
CCN(CC)CCSC(N=O)c1nc(C(C)(C)C)no1 = valid
CCN(CC)CCSC(N=O)c1nc(-c2cccc3ccccc23)no1 = valid
CCN(CC)CCSC(N=O)c1nc(Cc2ccccc2)no1 = valid
CCN(CC)CCSC(N=O)c1noc(-c2ccccc2)n1 = valid
COc1cc(S(=O)(=O)CCN(C)Cc2ccccc2)cc(OC)c1OC = valid
COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)CC(O)(C(C)=O)CC3OC1CC(N(CC#N)CC(=O)O)C(O)C(C)O1 = valid
CNS(=O)(=O)Cc1ccc2[nH]cc(CCN(C)C)c2c1 = valid
Cn1c(N)nc2cc(Cl)ccc21 = valid
O=C(OCCCl)n1cc(F)c(=O)[nH]c1=O = valid
CCOC(=O)C1=C(C)NC(C)=C(C(=O)OCC)C1c1ccccc1C=CC(=O)OC(C)(C)C = valid
CCC(O)(C(=O)O)c1ccc(CC(C)C)cc1 = valid
CCCC(=O)OCOc1ccccc1C(N)=O = valid
CC(C)(C)C(=O)OCOc1ccccc1C(N)=O = valid
COC(=O)Nc1ccccc1I = valid
CC1(C)CC(NC(=O)NP(=O)(N2CC2(C)C)N2CC2(C)C)CC(C)(C)N1O = valid
CC1(C)CC(NC(=O)NP(=O)(N2CC2)N2CC2)C(C)(C)N1O = valid
CC1(C)CC(NC(=O)NP(=O)(N2CC2(C)C)N2CC2(C)C)C(C)(C)N1O = valid
CC1(C)CC(NC(=O)NP(=O)(N2CC2(C)C)N2CC2(C)C)CC(C)(C)N1 = valid
CC1(C)CN1P(=O)(NC(=O)NC12CC3CC(CC(C3)C1)C2)N1CC1(C)C = valid
CCC1(C(=O)NC(C)c2ccc(Cl)cc2)C(C)C1(Cl)Cl = valid
c1cc(CN2CCCCC2)cc(OCCCNc2nc3ccccc3s2)c1 = valid
Cc1cnc(C2=NC(=O)C(C)(C(C)C)N2)c(C(=O)O)c1 = valid
COC(=O)c1c(C)no[n+]1[O-] = valid
COC(=O)c1no[n+]([O-])c1C = valid
CN(c1nc2ccccc2s1)C1CCN(CC(O)COc2ccc(F)cc2)CC1 = valid
O=C(CCN1CCC(O)(c2ccc(Cl)cc2)CC1)c1ccc(F)cc1 = valid
O=C1CC(C(=O)O)CC(=O)C1=C(O)C1CC1 = valid

In [10]:
print(len(valid_rows))

16067

In [11]:
df_valid_rows = pd.DataFrame(valid_rows)

In [12]:
df_valid_rows.head()

,SMILES,pIC50,mol,num_atoms,logP
0,O=S(=O)(Nc1cccc(-c2cnc3ccccc3n2)c1)c1cccs1,4.26,<rdkit.Chem.rdchem.Mol object at 0x7f59df45bc30>,25,4.1591
1,O=c1cc(-c2nc(-c3ccc(-c4cn(CCP(=O)(O)O)nn4)cc3)...,4.34,<rdkit.Chem.rdchem.Mol object at 0x7f59a320c9e0>,36,3.6743
2,NC(=O)c1ccc2c(c1)nc(C1CCC(O)CC1)n2CCCO,4.53,<rdkit.Chem.rdchem.Mol object at 0x7f59a320cac0>,23,1.5361
3,NCCCn1c(C2CCNCC2)nc2cc(C(N)=O)ccc21,4.56,<rdkit.Chem.rdchem.Mol object at 0x7f59a320cba0>,22,0.9510
4,CNC(=S)Nc1cccc(-c2cnc3ccccc3n2)c1,4.59,<rdkit.Chem.rdchem.Mol object at 0x7f59a320c7b0>,21,3.2130

In [13]:
df_valid_rows.tail()

,SMILES,pIC50,mol,num_atoms,logP
16062,S=C(NN=C(c1ccccn1)c1ccccn1)Nc1ccccc1,0.00,<rdkit.Chem.rdchem.Mol object at 0x7f59a314ed50>,24,3.21560
16063,S=C=NCCCCCCCCCCc1ccccc1,0.00,<rdkit.Chem.rdchem.Mol object at 0x7f59a314edc0>,19,5.45270
16064,S=C=NCCCCCCCCc1ccccc1,0.00,<rdkit.Chem.rdchem.Mol object at 0x7f59a314ee30>,17,4.67250
16065,S=c1[nH]nc(Cn2ccc3ccccc32)n1-c1ccccc1,0.00,<rdkit.Chem.rdchem.Mol object at 0x7f59a314eea0>,22,3.93289
16066,N=[N+]=NC=Cc1ccc([N+](=O)[O-])o1,0.02,<rdkit.Chem.rdchem.Mol object at 0x7f59a314ef10>,13,1.70887

In [14]:
df_valid_rows.to_csv("valid_smiles.csv",index=False)

In [15]:
check = pd.read_csv("valid_smiles.csv")

In [16]:
check.head()

,SMILES,pIC50,mol,num_atoms,logP
0,O=S(=O)(Nc1cccc(-c2cnc3ccccc3n2)c1)c1cccs1,4.26,<rdkit.Chem.rdchem.Mol object at 0x7f59df45bc30>,25,4.1591
1,O=c1cc(-c2nc(-c3ccc(-c4cn(CCP(=O)(O)O)nn4)cc3)...,4.34,<rdkit.Chem.rdchem.Mol object at 0x7f59a320c9e0>,36,3.6743
2,NC(=O)c1ccc2c(c1)nc(C1CCC(O)CC1)n2CCCO,4.53,<rdkit.Chem.rdchem.Mol object at 0x7f59a320cac0>,23,1.5361
3,NCCCn1c(C2CCNCC2)nc2cc(C(N)=O)ccc21,4.56,<rdkit.Chem.rdchem.Mol object at 0x7f59a320cba0>,22,0.9510
4,CNC(=S)Nc1cccc(-c2cnc3ccccc3n2)c1,4.59,<rdkit.Chem.rdchem.Mol object at 0x7f59a320c7b0>,21,3.2130

In [17]:
check.tail()

,SMILES,pIC50,mol,num_atoms,logP
16062,S=C(NN=C(c1ccccn1)c1ccccn1)Nc1ccccc1,0.00,<rdkit.Chem.rdchem.Mol object at 0x7f59a314ed50>,24,3.21560
16063,S=C=NCCCCCCCCCCc1ccccc1,0.00,<rdkit.Chem.rdchem.Mol object at 0x7f59a314edc0>,19,5.45270
16064,S=C=NCCCCCCCCc1ccccc1,0.00,<rdkit.Chem.rdchem.Mol object at 0x7f59a314ee30>,17,4.67250
16065,S=c1[nH]nc(Cn2ccc3ccccc32)n1-c1ccccc1,0.00,<rdkit.Chem.rdchem.Mol object at 0x7f59a314eea0>,22,3.93289
16066,N=[N+]=NC=Cc1ccc([N+](=O)[O-])o1,0.02,<rdkit.Chem.rdchem.Mol object at 0x7f59a314ef10>,13,1.70887